name: CMSSW Environment Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull CMSSW Docker image
      run: docker pull cmssw/cc7

    - name: Set up CVMFS
      uses: ./.github/workflows/cvmfs.yml

    - name: Set up CMSSW and HiggsCombine Tool
      run: |
        docker run --name my_cmssw_container -i -v /cvmfs:/workspace cmssw/cc7 /bin/bash -c "
          ls -al /cvmfs/
          source /cvmfs/cms.cern.ch/cmsset_default.sh 
          cd /workspace
          # Run your jobs here
          cmsrel CMSSW_11_3_4
          cd CMSSW_11_3_4/src
          cmsenv
          git clone https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit.git HiggsAnalysis/CombinedLimit "
          

    - name: Cleanup
      run: docker rm my_cmssw_container
