name: cvmfs test
on: [push]
    
jobs:
  ubuntu-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - name: Test CernVM-FS
      run: ls /cvmfs/sft.cern.ch/
