name: CMSSW container
on: [push]

jobs:
  cmssw-cc7:
    runs-on: ubuntu-latest
    container: 
      image: cmssw/cc7
      volumes:
        - /cvmfs:/workspace

    services:
      cvmfs:
       image: cvmfs/service
       env:
          CVMFS_REPOSITORIES: "cms.cern.ch"
          CVMFS_CLIENT_PROFILE: "single"
       options: --volume /cvmfs:/cvmfs:shared --device /dev/fuse --cap-add SYS_ADMIN
       

    steps:
      - name: Check cvmfs mount
        run: ls -al /cvmfs
